# Generated by Django 3.2.7 on 2021-10-30 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Найменование категории')),
                ('slug', models.SlugField(verbose_name='url')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Consecrated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Кому...')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя фото')),
                ('image', models.ImageField(upload_to='media')),
                ('date_add', models.DateTimeField(verbose_name='Дата добавления фото')),
            ],
            options={
                'ordering': ('-date_add',),
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Названия стиха')),
                ('text', models.TextField(verbose_name='Текст стиха')),
                ('date_of_creation', models.CharField(max_length=50, verbose_name='Дата написания')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления стиха')),
                ('publish', models.BooleanField(verbose_name='Опубликовать')),
                ('slug', models.SlugField(verbose_name='url')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='author_backend.category', verbose_name='Категория стиха')),
                ('consecrated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  to='author_backend.consecrated', verbose_name='Кому посвящається')),
            ],
            options={
                'ordering': ('-date_add',),
            },
        ),
    ]
